export const route = { path: '/super-admin/tenants/:id', index: false, auth: 'required', roles: ['super_admin'], title: 'تفاصيل المؤسسة' };

import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { BookOpen, GraduationCap, Wallet } from 'lucide-react';
import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';
import superAdminService from '../../services/superAdminService';

function Modal({ type, name, onCancel, onConfirm, loading }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-surface-default p-6 shadow-panel"><h3 className="text-xl font-bold">تأكيد الإجراء</h3><p className="mt-3 text-ink-600">{type === 'delete' ? <>سيتم تعطيل المؤسسة <b>{name}</b>. هذا حذف منطقي/تعطيل وليس فقداناً دائماً للبيانات.</> : <>سيتم تعليق اشتراك <b>{name}</b> حتى تتم إعادة تفعيله.</>}</p><div className="mt-6 flex gap-3"><Button onClick={onConfirm} disabled={loading}>تأكيد</Button><Button variant="subtle" onClick={onCancel}>إلغاء</Button></div></div></div>; }
export default function TenantDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [tenant, setTenant] = useState(null), [stats, setStats] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [modal, setModal] = useState(null), [working, setWorking] = useState(false);
  useEffect(() => { Promise.all([superAdminService.getTenant(id), superAdminService.getTenantStats(id)]).then(([tenantRes, statsRes]) => { setTenant(tenantRes.data.data); setStats(statsRes.data.data); }).catch((err) => setError(err?.message || 'تعذر تحميل المؤسسة.')).finally(() => setLoading(false)); }, [id]);
  const action = async () => { setWorking(true); try { if (modal === 'delete') { await superAdminService.deleteTenant(id); navigate('/super-admin/tenants', { replace: true }); } else { const next = tenant.subscriptionStatus === 'suspended' ? 'active' : 'suspended'; const res = await superAdminService.updateTenant(id, { subscriptionStatus: next }); setTenant(res.data.data); setModal(null); } } catch (err) { setError(err?.message || 'تعذر تنفيذ الإجراء.'); } finally { setWorking(false); } };
  if (loading) return <div className="rounded-2xl bg-surface-default p-8 text-ink-500">جارٍ تحميل المؤسسة...</div>; if (error) return <div className="rounded-2xl bg-danger-soft p-5 text-danger-DEFAULT">{error}<Link className="mr-3 underline" to="/super-admin/tenants">عودة للقائمة</Link></div>;
  const metric = [{ label: 'الطلاب', value: stats.studentCount, icon: GraduationCap }, { label: 'الدورات', value: stats.courseCount, icon: BookOpen }, { label: 'إيراد ناجح', value: `${Number(stats.successfulTransactionAmount).toLocaleString('ar-EG')} ج.م`, icon: Wallet }];
  return <div className="space-y-6"><Link to="/super-admin/tenants" className="text-sm font-bold text-brand-600">← جميع المؤسسات</Link><section className="rounded-2xl border border-surface-border bg-surface-default p-6 shadow-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-3xl font-bold">{tenant.name}</h2><p className="mt-2 text-ink-500">{tenant.subdomain}</p><div className="mt-4 flex gap-2"><Badge variant={tenant.subscriptionStatus === 'suspended' ? 'danger' : tenant.subscriptionStatus === 'trial' ? 'info' : 'success'}>{tenant.subscriptionStatus}</Badge><Badge variant={tenant.isActive ? 'success' : 'danger'}>{tenant.isActive ? 'مفعلة' : 'معطلة'}</Badge></div></div><div className="flex flex-wrap gap-2">{tenant.subscriptionStatus === 'suspended' ? <Button onClick={() => setModal('reactivate')}>إعادة تفعيل</Button> : <Button variant="subtle" className="text-danger-DEFAULT" onClick={() => setModal('suspend')}>تعليق الاشتراك</Button>}<Button variant="subtle" className="text-danger-DEFAULT" onClick={() => setModal('delete')}>تعطيل المؤسسة</Button></div></div></section><section className="grid gap-4 md:grid-cols-3">{metric.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl border border-surface-border bg-surface-default p-5 shadow-card"><Icon className="text-brand-600" /><p className="mt-4 text-2xl font-bold">{value}</p><p className="mt-1 text-sm text-ink-500">{label}</p></div>)}</section>{modal && <Modal type={modal} name={tenant.name} loading={working} onCancel={() => setModal(null)} onConfirm={action} />}</div>;
}
