export const route = { path: '/super-admin/tenants/new', index: false, auth: 'required', roles: ['super_admin'], title: 'إضافة مؤسسة' };

import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { Link } from 'react-router-dom';
import Input from '../../components/ui/Input';
import Button from '../../components/ui/Button';
import superAdminService from '../../services/superAdminService';

const initial = { name: '', subdomain: '', adminName: '', adminEmail: '', adminPassword: '' };
export default function TenantCreatePage() {
  const [form, setForm] = useState(initial), [error, setError] = useState(''), [loading, setLoading] = useState(false), [created, setCreated] = useState(null), [copied, setCopied] = useState(false);
  const update = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setError(''); const subdomain = form.subdomain.trim().toLowerCase(); if (!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(subdomain)) return setError('النطاق الفرعي يجب أن يحتوي أحرفاً صغيرة وأرقاماً وشرطات فقط، بطول 1–63.'); setLoading(true); try { const res = await superAdminService.createTenant({ name: form.name, subdomain, admin: { name: form.adminName, email: form.adminEmail, password: form.adminPassword } }); setCreated({ ...res.data.data, password: form.adminPassword }); } catch (err) { setError(err?.status === 409 ? 'يوجد بالفعل نطاق فرعي أو بريد مدير مطابق.' : err?.message || 'تعذر إنشاء المؤسسة.'); } finally { setLoading(false); } };
  const copy = async () => { await navigator.clipboard?.writeText(created.password); setCopied(true); };
  if (created) return <div className="mx-auto max-w-2xl rounded-2xl border border-success-DEFAULT/30 bg-surface-default p-7 shadow-card"><h2 className="text-2xl font-bold">تم إنشاء المؤسسة بنجاح</h2><p className="mt-2 text-ink-500">احفظ بيانات المدير الآن؛ لن تظهر كلمة المرور مرة أخرى.</p><div className="mt-6 space-y-3 rounded-xl bg-surface-muted p-4 text-sm"><p><b>المؤسسة:</b> {created.tenant.name}</p><p><b>البريد:</b> {created.admin.email}</p><div className="flex items-center justify-between gap-3"><span><b>كلمة المرور المؤقتة:</b> {created.password}</span><button type="button" onClick={copy} className="rounded-lg p-2 text-brand-600 hover:bg-surface-default" aria-label="نسخ كلمة المرور">{copied ? <Check size={18} /> : <Copy size={18} />}</button></div></div><Link to="/super-admin/tenants" className="mt-6 inline-block font-bold text-brand-600">الانتقال إلى قائمة المؤسسات</Link></div>;
  return <div className="mx-auto max-w-2xl"><h2 className="text-3xl font-bold">إضافة مؤسسة جديدة</h2><p className="mt-2 text-ink-500">أنشئ المؤسسة وحساب مديرها الأول.</p><form onSubmit={submit} className="mt-6 space-y-5 rounded-2xl border border-surface-border bg-surface-default p-6 shadow-card">{error && <div className="rounded-xl bg-danger-soft p-3 text-sm text-danger-DEFAULT">{error}</div>}<div><label className="mb-2 block text-sm font-bold">اسم المؤسسة</label><Input name="name" value={form.name} onChange={update} required /></div><div><label className="mb-2 block text-sm font-bold">النطاق الفرعي</label><Input name="subdomain" value={form.subdomain} onChange={update} required placeholder="my-school" /><p className="mt-2 text-xs text-ink-500">أحرف صغيرة وأرقام وشرطات، من دون مسافات.</p></div><hr className="border-surface-border" /><h3 className="font-bold">بيانات المدير</h3><div className="grid gap-4 sm:grid-cols-2"><Input name="adminName" value={form.adminName} onChange={update} required placeholder="اسم المدير" /><Input name="adminEmail" type="email" value={form.adminEmail} onChange={update} required placeholder="البريد الإلكتروني" /></div><Input name="adminPassword" type="password" value={form.adminPassword} onChange={update} required placeholder="كلمة المرور المؤقتة" /><Button type="submit" disabled={loading}>{loading ? 'جارٍ الإنشاء...' : 'إنشاء المؤسسة'}</Button></form></div>;
}
