import React, { useEffect, useState } from 'react';
import Button from '../ui/Button';
import Input from '../ui/Input';
import api from '../../services/api';

function CopyCodeButton({ code }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { try { await navigator.clipboard.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch {} };
  return <Button type="button" size="sm" variant="ghost" onClick={copy} aria-label="نسخ الكود">{copied ? '✓' : 'نسخ'}</Button>;
}

export default function CourseAccessCodeGenerator({ instructorId, canGenerate }) {
  const [type, setType] = useState('full_course'); const [courses, setCourses] = useState([]); const [courseId, setCourseId] = useState(''); const [lectures, setLectures] = useState([]); const [lectureId, setLectureId] = useState(''); const [count, setCount] = useState(1); const [codes, setCodes] = useState([]); const [error, setError] = useState(''); const [allCopied, setAllCopied] = useState(false);
  useEffect(() => { api.get(`/instructors/${instructorId}/courses`).then((r) => { const items = r.data.data || []; setCourses(items); setCourseId(items[0]?._id || ''); }).catch((e) => setError(e?.message || 'تعذر تحميل الكورسات.')); }, [instructorId]);
  useEffect(() => { if (type !== 'single_lecture' || !courseId) return; api.get(`/instructors/${instructorId}/courses/${courseId}/lectures`).then((r) => { const items = r.data.data || []; setLectures(items); setLectureId(items[0]?._id || ''); }).catch((e) => setError(e?.message || 'تعذر تحميل المحاضرات.')); }, [instructorId, courseId, type]);
  const generate = async (event) => { event.preventDefault(); try { const r = await api.post(`/instructors/${instructorId}/courses/${courseId}/access-codes/generate`, { type, count: Number(count), ...(type === 'single_lecture' ? { lectureId } : {}) }); setCodes(r.data.data.codes || []); setError(''); } catch (e) { setError(e?.message || 'تعذر توليد الأكواد.'); } };
  const copyAll = async () => { try { await navigator.clipboard.writeText(codes.join('\n')); setAllCopied(true); setTimeout(() => setAllCopied(false), 1500); } catch { setError('تعذر نسخ الأكواد.'); } };
  return <section className="rounded-2xl bg-surface-default shadow-card p-6 space-y-3"><h2 className="font-semibold">أكواد الوصول</h2><p className="text-sm text-ink-500">اختر كود الكورس كامل أو كود محاضرة واحدة. أكواد شحن المحفظة بالأسفل.</p>{error && <p className="text-sm text-danger-DEFAULT">{error}</p>}<form onSubmit={generate} className="grid gap-3 md:grid-cols-4 items-end"><label>النوع<select className="input w-full" value={type} onChange={(e) => setType(e.target.value)}><option value="full_course">كورس كامل</option><option value="single_lecture">محاضرة واحدة</option></select></label><label>الكورس<select className="input w-full" value={courseId} onChange={(e) => setCourseId(e.target.value)}>{courses.map((x) => <option key={x._id} value={x._id}>{x.title_ar || x.title_en}</option>)}</select></label>{type === 'single_lecture' && <label>المحاضرة<select className="input w-full" value={lectureId} onChange={(e) => setLectureId(e.target.value)}>{lectures.map((x) => <option key={x._id} value={x._id}>{x.order}. {x.title_ar || x.title_en}</option>)}</select></label>}<label>الكمية<Input type="number" min="1" value={count} onChange={(e) => setCount(e.target.value)} /></label><Button type="submit" disabled={!canGenerate || !courseId || (type === 'single_lecture' && !lectureId)}>توليد</Button></form>{codes.length > 0 && <div className="rounded-xl bg-success-soft p-3"><b>{type === 'full_course' ? 'دفعة: كورس كامل' : 'دفعة: محاضرة واحدة'}</b><Button type="button" size="sm" variant="subtle" onClick={copyAll}>{allCopied ? '✓ تم النسخ' : 'نسخ الكل'}</Button><div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-2">{codes.map((code) => <div key={code} className="flex items-center justify-between rounded bg-surface-default px-2 py-1"><code>{code}</code><CopyCodeButton code={code} /></div>)}</div></div>}</section>;
}
